### ISSUE TITLE
Warnings found and function button not working

### ISSUE THREAD

**Issue by gauravjee** [azw409/BitX40-RaduinoExtra#1]
C:\GS\Personal\7. HAM\BItx\BitXtra40\BitXtra40.ino: In function 'void calibrate()':

C:\GS\Personal\7. HAM\BItx\BitXtra40\BitXtra40.ino:435:36: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       printLine1("Calibrated      ");

                                    ^

C:\GS\Personal\7. HAM\BItx\BitXtra40\BitXtra40.ino:444:30: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

       printLine2("Saved.    ");

                              ^

C:\GS\Personal\7. HAM\BItx\BitXtra40\BitXtra40.ino: In function 'void checkButton()':

C:\GS\Personal\7. HAM\BItx\BitXtra40\BitXtra40.ino:554:29: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

     printLine2("VFOs reset!");

                             ^

Sketch uses 20880 bytes (67%) of program storage space. Maximum is 30720 bytes.
Global variables use 818 bytes (39%) of dynamic memory, leaving 1230 bytes for local variables. Maximum is 2048 bytes.

**Comment by gauravjee** [comment]
Also the function button is not working

**Comment by gauravjee** [comment]
S Meter works perfectly... 
Can you share the wiring diagram for CW and function buttons

**Comment by azw409** [comment]
Hi Gaurav, this is the wiring diagram for CW http://bitxhacks.blogspot.co.uk/2017/02/putting-bitx-raduino-on-cw.html
The function buttons just short the pin to ground. Function button 2 is D3 and Function button 1 is A3. I currently only use D3.
